### ISSUE TITLE
File Logger doesn't output initial configuration load

### ISSUE THREAD

**Issue by ElliotAlexander** [ElliotAlexander/Runway_Redeclaration_Tool#1]
FileLogger now depends on the config manager, which needs to load before it, hence errors from config manager will only be outputted in Stdout not in the logfiles. 

![screenshot_2](https://user-images.githubusercontent.com/7238161/37579987-36e63a1e-2b39-11e8-9d87-d69a4bc75d89.png)

**Comment by ElliotAlexander** [comment]
My proposed solution would be to add a Debug option in the config file. i.e. if the user is having problems loading their config file, they can enable the debug option and the file logger will use a set of 'default' log values, initialising before the config manager, giving the user less granular control but full logs.

**Comment by adelaidaCreosteanu** [comment]
That sounds good.

I want to make sure that the purpose of the file logger is clear to us: we're using it for the development of the tool, right? We would have some logging commands in the code and when we use the application, we want to see that everything is happening correctly, and if it's not, we get more info about what's wrong from the logs. But we're not thinking that the user of the application will use the logs, right? Because I think they want a finished product. They wouldn't be able to debug an issue, so there's wouldn't be a point to a 'Debug option'.
What do other people think?

**Comment by ElliotAlexander** [comment]
Okay, I'll add in that option as a TODO for the moment, and add funcitonality once the work for this sprint is done. 

I'm personally okay with leaving the file logger in the finished product, the argument can be made that in a 'real world' (i.e. we're actually deploying this as a product to the user) if there ever was a problem witih the application, say it doesn't run on a particular system, won't import an XML file, etc, the user could return log files and the problem could be diagnosed with significantly less effort. Obviously they're never going to be using the logs themselves, but as a maintenance (and as you say development tool) I think they could be an important feature.

**Comment by ElliotAlexander** [comment]
@adelaidaCreosteanu I think I've got a decent solution. See #855b95f. I'm buffering the output prior to the initalisation of FileLogger. I'll leave the issue open for comment.
